server:
  port: 8080
  servlet:
    context-path:  /appchat
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/appchatdb"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

